name: build deb package
run-name: ${{ gitea.actor }} is building dsr
on: [push]

jobs:
  build-deb:
    runs-on: automatl-net8-ubuntu2204
    if: gitea.ref == 'refs/heads/master'
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: build deb
        run: |
          dotnet deb install && dotnet publish -c Release -r linux-x64 -f net8.0 --self-contained -t:CreateDeb
      - name: rename deb
        run: |
          mv dsr/bin/Release/net8.0/linux-x64/dsr*.deb dsr.deb
      - name: upload deb
        run: |
          curl --fail-with-body --no-progress-meter -i -w "\n\n" --user ${{ secrets.CI_USER }}:${{ secrets.CI_TOKEN }} --upload-file dsr.deb https://${{ vars.AU_GITEA_HOST }}/api/packages/audist/debian/pool/jammy/main/upload
